// Array containing 100 different topics
const topics = [
    // Add your topics here
    
    'History of Ancient Egypt',
    'The Theory of Relativity',
    'Climate Change and Global Warming',
    'Artificial Intelligence',
    'Evolutionary Biology',
    'Cryptocurrencies and Blockchain',
    'World War II',
    'Space Exploration',
    'Psychology and Mental Health',
    'Sustainable Energy Sources',
    'Philosophy of Mind',
    'Human Rights and Social Justice',
    'The Renaissance Period',
    'Genetic Engineering',
    'The History of Jazz Music',
    'Environmental Conservation',
    'The Industrial Revolution',
    'The Theory of Evolution',
    'The History of Photography',
    'Cosmology and the Big Bang',
    'The Cold War',
    'The Human Genome Project',
    'The History of Ancient Rome',
    'Climate Change Mitigation Strategies',
    'Neuroscience and Brain Function',
    'The History of Classical Music',
    'The Future of Space Travel',
    'Sociology and Cultural Studies',
    'Renewable Energy Technologies',
    'The Philosophy of Ethics',
    'The French Revolution',
    'Medical Breakthroughs and Innovations',
    'The History of Film and Cinema',
    'The Origins of Life on Earth',
    'The History of Modern Art',
    'Digital Privacy and Security',
    'The History of Ancient Greece',
    'The Impacts of Technology on Society',
    'The American Civil Rights Movement',
    'The History of World Religions',
    'The Implications of Artificial Intelligence',
    'The History of Ancient China',
    'The Future of Robotics',
    'The Philosophy of Existentialism',
    'The World Wars and their Consequences',
    'The History of Ancient Mesopotamia',
    'The Role of Social Media in Modern Society',
    'The History of Western Philosophy',
    'The Impacts of Climate Change on Ecosystems',
    'The History of Ancient India',
    'Ethical Dilemmas in Science and Technology',
    'The History of European Exploration',
    'The Psychology of Decision Making',
    'The History of Ancient Maya Civilization',
    'The Impacts of Globalization',
    'The History of African Civilizations',
    'The Future of Artificial Intelligence',
    'The Philosophy of Aesthetics',
    'The History of Ancient Persia',
    'The Impacts of Social Media on Communication',
    'The History of Ancient Mesoamerica',
    'The Psychology of Personality',
    'The History of Ancient Japan',
    'The Implications of Genetic Engineering',
    'The History of Ancient Native American Cultures',
    'The Philosophy of Morality',
    'The Impacts of Climate Change on Human Health',
    'The History of Ancient Egypt',
    'The Future of Renewable Energy',
    'The History of Ancient Greece',
    'The Psychology of Emotions',
    'The History of Ancient Rome',
    'The Impacts of Artificial Intelligence on Jobs',
    'The History of Ancient China',
    'The Philosophy of Free Will',
    'The Impacts of Technology on Mental Health',
    'The History of Ancient India',
    'The Future of Space Exploration',
    'The History of Ancient Mesopotamia',
    'The Psychology of Learning and Memory',
    'The History of Ancient Maya Civilization',
    'The Implications of Virtual Reality',
    'The History of African Civilizations',
    'The Philosophy of Consciousness',
    'The Impacts of Climate Change on Wildlife',
    'The History of Ancient Persia',
    'The Role of Artificial Intelligence in Healthcare',
    'The History of Ancient Mesoamerica',
    'The Psychology of Motivation',
    'The History of Ancient Japan',
    'The Implications of Nanotechnology',
    'The History of Ancient Greece',
    "Animals",
  "Art",
  "Business",
  "Career",
  "Communication",
  "Creativity",
  "Dreams",
  "Education",
  "Empathy",
  "Finance",
  "Food",
  "Friendship",
  "Health",
  "Hobbies",
  "Humor",
  "Leadership",
  "Love",
  "Music",
  "Nature",
  "Peace",
  "Philosophy",
  "Photography",
  "Politics",
  "Problem Solving",
  "Religion",
  "Relationships",
  "Science",
  "Self-Improvement",
  "Travel",
  "Violence",
  "War",
  "Work",
  "Writing",
  "Adventure",
  "Activism",
  "Change",
  "Choice",
  "Courage",
  "Creativity",
  "Dreams",
  "Failure",
  "Family",
  "Fear",
  "Friendship",
  "Giving",
  "Growth",
  "Hope",
  "Humor",
  "Inspiration",
  "Learning",
  "Love",
  "Meaning",
  "Passion",
  "Peace",
  "Perspective",
  "Perseverance",
  "Purpose",
  "Rebirth",
  "Relationships",
  "Resilience",
  "Risk",
  "Self-Discovery",
  "Self-Love",
  "Success",
  "Trust",
  "Wisdom",
  "Wonder",
];

const topicDisplay = document.getElementById('topic-display');
const generateButton = document.getElementById('generate-button');
const darkModeToggle = document.getElementById('dark-mode-toggle');

// Function to generate a random topic
function generateRandomTopic() {
    const randomIndex = Math.floor(Math.random() * topics.length);
    topicDisplay.textContent = topics[randomIndex];
}

// Event listener for the generate button
generateButton.addEventListener('click', generateRandomTopic);

// Function to toggle between light and dark modes
function toggleDarkMode() {
    document.body.classList.toggle('dark-mode');
    document.querySelector('.container').classList.toggle('dark-mode');
    document.querySelector('h1').classList.toggle('dark-mode');
    document.querySelector('#topic-display').classList.toggle('dark-mode');
    document.querySelector('button').classList.toggle('dark-mode');
    document.querySelectorAll('.slider').forEach(function(element) {
    element.classList.toggle('dark-mode');
    });
  }
  
// Event listener for the dark mode toggle
darkModeToggle.addEventListener('change', toggleDarkMode);
